apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-acs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-acs 
  name: rhtap-acs
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-acs 
